"""
Presales Digital Twin — Main FastAPI Application
=================================================
This is the single entry point. Each module's router is imported and mounted here.
DO NOT edit this file unless you are the project lead.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.routes import module1_routes, module2_routes, module3_routes, module4_routes

app = FastAPI(
    title="Presales Digital Twin",
    description="AI-powered presales assistant for solution architects",
    version="0.1.0",
)

# -- CORS (allow frontend to call backend) --
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# -- Mount each module's router --
app.include_router(
    module1_routes.router,
    prefix="/api/v1/intel",
    tags=["Module 1: Pre-Meeting Intelligence"],
)
app.include_router(
    module2_routes.router,
    prefix="/api/v1/architecture",
    tags=["Module 2: Architecture Drafting"],
)
app.include_router(
    module3_routes.router,
    prefix="/api/v1/financial",
    tags=["Module 3: Financial Modeling"],
)
app.include_router(
    module4_routes.router,
    prefix="/api/v1/redteam",
    tags=["Module 4: Red Team & Compliance"],
)


@app.get("/health", tags=["System"])
def health_check():
    return {"status": "ok", "service": "presales-digital-twin"}
